# Classic framed menu style
path=bg:#202020,fg:#ffffff list=bg:#303030,fg:#eeeeee separator=bg:#505050 selection=bg:#ffffff,fg:#000000,bold frame=bg:#707070 body=bg:#202020 help=bg:#202020,fg:#cccccc
