# Default kconfiglib menu style
path=bg:#51589e,fg:#E6DFF5 list=bg:#B5D7F8,fg:#505E73 separator=bg:#6684DC selection=fg:#1F1A20,bg:#A4C2F2,bold,underline frame=bg:#494f8f body=bg:#6169be help=bg:#51589e,fg:#E6DFF5
