#pragma once

#define EXCEPTION_TYPE_SYNCHRONOUS  0
#define EXCEPTION_TYPE_IRQ          1
#define EXCEPTION_TYPE_FIQ          2
#define EXCEPTION_TYPE_SERROR       3

#define EXCEPTION_OFFSET_CURRENT_EL_SP0_SYNCHRONOUS 0x0
#define EXCEPTION_OFFSET_CURRENT_EL_SP0_IRQ 0x80
#define EXCEPTION_OFFSET_CURRENT_EL_SP0_FIQ 0x100
#define EXCEPTION_OFFSET_CURRENT_EL_SP0_SERROR 0x180
#define EXCEPTION_OFFSET_CURRENT_EL_SPX_SYNCHRONOUS 0x200
#define EXCEPTION_OFFSET_CURRENT_EL_SPX_IRQ 0x280
#define EXCEPTION_OFFSET_CURRENT_EL_SPX_FIQ 0x300
#define EXCEPTION_OFFSET_CURRENT_EL_SPX_SERROR 0x380
#define EXCEPTION_OFFSET_LOWER_EL_AARCH64_SYNCHRONOUS 0x400
#define EXCEPTION_OFFSET_LOWER_EL_AARCH64_IRQ 0x480
#define EXCEPTION_OFFSET_LOWER_EL_AARCH64_FIQ 0x500
#define EXCEPTION_OFFSET_LOWER_EL_AARCH64_SERROR 0x580
#define EXCEPTION_OFFSET_LOWER_EL_AARCH32_SYNCHRONOUS 0x600
#define EXCEPTION_OFFSET_LOWER_EL_AARCH32_IRQ 0x680
#define EXCEPTION_OFFSET_LOWER_EL_AARCH32_FIQ 0x700
#define EXCEPTION_OFFSET_LOWER_EL_AARCH32_SERROR 0x780