#pragma once
#include <include/config.h> // config.h is generated by build system

// Page Size: 4KiB. Common page size on most arm64 chips.
#ifdef CONFIG_ARM64_PAGE_SIZE_4K
#define ARM64_PAGE_TABLE_SIZE 0x1000ULL
#elif defined(CONFIG_ARM64_PAGE_SIZE_16K)
#define ARM64_PAGE_TABLE_SIZE 0x4000ULL
#elif defined(CONFIG_ARM64_PAGE_SIZE_64K)
#define ARM64_PAGE_TABLE_SIZE 0x10000ULL
#else
#error "No page size configured"
#endif

// Compute TGx encoding from ARM64_PAGE_TABLE_SIZE. x: 0->TG0, 1->TG1
#define ARM64_TCR_TG(x)                     \
    (((ARM64_PAGE_TABLE_SIZE) == 0x1000)    \
         ? ((x) == 0 ? 0b00 : 0b10)         \
     : ((ARM64_PAGE_TABLE_SIZE) == 0x10000) \
         ? ((x) == 0 ? 0b01 : 0b11)         \
         : ((x) == 0 ? 0b10 : 0b01))
