#pragma once

#include <bitops.h>

enum qupv3_se_type
{
    QUPV3_NONE = 0,
    QUPV3_SPI,
    QUPV3_UART,
    QUPV3_I2C,
    QUPV3_I3C,
    QUPv3_SLAVE_SPI,
};

#define HWIO(name) HWIO_##name
/* Common */
#define HWIO_SE_GENI_BASE (0x99c000)

#define HWIO_SE_GENI_FORCE_DEFAULT_REG          (HWIO_SE_GENI_BASE + 0x20)
#define BIT_SE_GENI_FORCE_DEFAULT_FORCE_DEFAULT BIT(0)

#define HWIO_SE_GENI_OUTPUT_CTRL                (HWIO_SE_GENI_BASE + 0x24)
#define BIT_SE_GENI_OUTPUT_CTRL_DEFAULT_IO_OUTPUT_CTRL  GENBITS(6, 0)

#define HWIO_SE_GENI_CGC_CTRL                   (HWIO_SE_GENI_BASE + 0x28)
#define BIT_SE_GENI_CGC_CTRL_DEFAULT_CGC_EN     BIT(0) | BIT(1) | BIT(2) | BIT(3) | BIT(4) | BIT(5) | BIT(6)

#define HWIO_SE_GENI_FW_REVISION_RO             (HWIO_SE_GENI_BASE + 0x68)
#define BIT_SE_GENI_FW_REVISION_RO_FW_REV_PROTOCOL     GENBITS(15, 8)
#define SFT_SE_GENI_FW_REVISION_RO_FW_REV_PROTOCOL     8

#define HWIO_SE_GENI_DMA_MODE_EN                    (HWIO_SE_GENI_BASE + 0x258)
#define BIT_SE_GENI_DMA_MODE_EN_GENI_DMA_MODE_EN    BIT(0)

#define HWIO_SE_GENI_TX_WATERMARK_REG       (HWIO_SE_GENI_BASE + 0x80c)
#define HWIO_SE_GENI_RX_WATERMARK_REG       (HWIO_SE_GENI_BASE + 0x810)
#define HWIO_SE_GENI_RX_RFR_WATERMARK_REG   (HWIO_SE_GENI_BASE + 0x814)

#define HWIO_SE_GSI_EVENT_EN                        (HWIO_SE_GENI_BASE + 0xe18)
#define HWIO_SE_GENI_M_IRQ_CLR                      (HWIO_SE_GENI_BASE + 0x618)
#define BIT_SE_GENI_M_IRQ_CLR_M_CMD_DONE_CLR        BIT(0)
#define BIT_SE_GENI_M_IRQ_CLR_M_TX_FIFO_WATERMARK_CLR     BIT(30)

#define HWIO_SE_DMA_TX_IRQ_CLR  (HWIO_SE_GENI_BASE + 0xc44)
#define HWIO_SE_DMA_RX_IRQ_CLR  (HWIO_SE_GENI_BASE + 0xd44)
#define HWIO_SE_IRQ_EN          (HWIO_SE_GENI_BASE + 0xe1c)
#define BIT_SE_IRQ_EN_DMA_RX_IRQ_EN    BIT(0)
#define BIT_SE_IRQ_EN_DMA_TX_IRQ_EN    BIT(1)
#define BIT_SE_IRQ_EN_GENI_M_IRQ_EN    BIT(2)
#define BIT_SE_IRQ_EN_GENI_S_IRQ_EN    BIT(3)

#define HWIO_SE_DMA_GENERAL_CFG (HWIO_SE_GENI_BASE + 0xe30)
#define BIT_SE_DMA_GENERAL_CFG_DMA_RX_CLK_CGC_ON        BIT(0)
#define BIT_SE_DMA_GENERAL_CFG_DMA_TX_CLK_CGC_ON        BIT(1)
#define BIT_SE_DMA_GENERAL_CFG_DMA_AHB_SLV_CFG_ON       BIT(2)
#define BIT_SE_DMA_GENERAL_CFG_AHB_SEC_SLV_CLK_CGC_ON   BIT(3)
#define BIT_SE_DMA_GENERAL_CFG_DUMMY_RX_NON_BUFFERABLE  BIT(4)
#define BIT_SE_DMA_GENERAL_CFG_RX_DMA_ZERO_PADDING_EN   BIT(5)
#define BIT_SE_DMA_GENERAL_CFG_RX_DMA_IRQ_DELAY            GENBITS(8, 6)

#define HWIO_SE_GENI_M_CMD0             (HWIO_SE_GENI_BASE + 0x600)
#define BIT_SE_GENI_M_CMD0_M_OPCODE     GENBITS(31, 27)
#define SFT_SE_GENI_M_CMD0_M_OPCODE     27
#define BIT_SE_GENI_M_CMD0_M_PARAMS     GENBITS(26, 0)

#define HWIO_SE_GENI_M_CMD_CTRL_REG		(HWIO_SE_GENI_BASE + 0x604)
#define BIT_SE_GENI_M_CMD_CTRL_REG_M_GENI_CMD_CANCEL       BIT(2)
#define BIT_SE_GENI_M_CMD_CTRL_REG_M_GENI_CMD_ABORT        BIT(1)
#define BIT_SE_GENI_M_CMD_CTRL_REG_M_GENI_DISABLE          BIT(0)

// GENI_M_IRQ_STATUS
#define HWIO_SE_GENI_M_IRQ_STATUS                   (HWIO_SE_GENI_BASE + 0x610)
#define BIT_SE_GENI_M_IRQ_STATUS_M_CMD_DONE         BIT(0)
#define BIT_SE_GENI_M_IRQ_STATUS_M_CMD_OVERRUN      BIT(1)
#define BIT_SE_GENI_M_IRQ_STATUS_M_ILLEGAL_CMD      BIT(2)
#define BIT_SE_GENI_M_IRQ_STATUS_M_CMD_FAILURE      BIT(3)
#define BIT_SE_GENI_M_IRQ_STATUS_M_CMD_CANCEL       BIT(4)
#define BIT_SE_GENI_M_IRQ_STATUS_M_CMD_ABORT        BIT(5)
#define BIT_SE_GENI_M_IRQ_STATUS_M_TIMESTAMP        BIT(6)
#define BIT_SE_GENI_M_IRQ_STATUS_M_RX_IRQ           BIT(7)
#define BIT_SE_GENI_M_IRQ_STATUS_M_GP_SYNC_IRQ_0    BIT(8)
#define BIT_SE_GENI_M_IRQ_STATUS_M_GP_IRQ_0         BIT(9)
#define BIT_SE_GENI_M_IRQ_STATUS_M_GP_IRQ_1         BIT(10)
#define BIT_SE_GENI_M_IRQ_STATUS_M_GP_IRQ_2         BIT(11)
#define BIT_SE_GENI_M_IRQ_STATUS_M_GP_IRQ_3         BIT(12)
#define BIT_SE_GENI_M_IRQ_STATUS_M_GP_IRQ_4         BIT(13)
#define BIT_SE_GENI_M_IRQ_STATUS_M_GP_IRQ_5         BIT(14)
#define BIT_SE_GENI_M_IRQ_STATUS_M_HW_IRQ           BIT(20)
#define BIT_SE_GENI_M_IRQ_STATUS_M_TX_FIFO_NOT_EMPTY    BIT(21)
#define BIT_SE_GENI_M_IRQ_STATUS_M_IO_DATA_DEASSERT     BIT(22)
#define BIT_SE_GENI_M_IRQ_STATUS_M_IO_DATA_ASSERT       BIT(23)
#define BIT_SE_GENI_M_IRQ_STATUS_M_RX_FIFO_RD_ERR       BIT(24)
#define BIT_SE_GENI_M_IRQ_STATUS_M_RX_FIFO_WR_ERR       BIT(25)
#define BIT_SE_GENI_M_IRQ_STATUS_M_RX_FIFO_WATERMARK    BIT(26)
#define BIT_SE_GENI_M_IRQ_STATUS_M_RX_FIFO_LAST         BIT(27)
#define BIT_SE_GENI_M_IRQ_STATUS_M_TX_FIFO_RD_ERR       BIT(28)
#define BIT_SE_GENI_M_IRQ_STATUS_M_TX_FIFO_WR_ERR       BIT(29)
#define BIT_SE_GENI_M_IRQ_STATUS_M_TX_FIFO_WATERMARK    BIT(30)
#define BIT_SE_GENI_M_IRQ_STATUS_M_SEC_IRQ              BIT(31)

#define HWIO_SE_GENI_M_IRQ_EN   (HWIO_SE_GENI_BASE + 0x614)
#define BIT_SE_GENI_M_IRQ_EN_M_CMD_DONE_EN           BIT(0)
#define BIT_SE_GENI_M_IRQ_EN_M_CMD_OVERRUN_EN        BIT(1)
#define BIT_SE_GENI_M_IRQ_EN_M_ILLEGAL_CMD_EN        BIT(2)
#define BIT_SE_GENI_M_IRQ_EN_M_CMD_FAILURE_EN        BIT(3)
#define BIT_SE_GENI_M_IRQ_EN_M_CMD_CANCEL_EN         BIT(4)
#define BIT_SE_GENI_M_IRQ_EN_M_CMD_ABORT_EN          BIT(5)
#define BIT_SE_GENI_M_IRQ_EN_M_TIMESTAMP_EN          BIT(6)
#define BIT_SE_GENI_M_IRQ_EN_M_RX_IRQ_EN             BIT(7)
#define BIT_SE_GENI_M_IRQ_EN_M_GP_SYNC_IRQ_0_EN      BIT(8)
#define BIT_SE_GENI_M_IRQ_EN_M_GP_IRQ_0_EN           BIT(9)
#define BIT_SE_GENI_M_IRQ_EN_M_GP_IRQ_1_EN           BIT(10)
#define BIT_SE_GENI_M_IRQ_EN_M_GP_IRQ_2_EN           BIT(11)
#define BIT_SE_GENI_M_IRQ_EN_M_GP_IRQ_3_EN           BIT(12)
#define BIT_SE_GENI_M_IRQ_EN_M_GP_IRQ_4_EN           BIT(13)
#define BIT_SE_GENI_M_IRQ_EN_M_GP_IRQ_5_EN           BIT(14)
#define BIT_SE_GENI_M_IRQ_EN_M_TX_FIFO_NOT_EMPTY_EN  BIT(21)
#define BIT_SE_GENI_M_IRQ_EN_M_IO_DATA_DEASSERT_EN   BIT(22)
#define BIT_SE_GENI_M_IRQ_EN_M_IO_DATA_ASSERT_EN     BIT(23)
#define BIT_SE_GENI_M_IRQ_EN_M_RX_FIFO_RD_ERR_EN     BIT(24)
#define BIT_SE_GENI_M_IRQ_EN_M_RX_FIFO_WR_ERR_EN     BIT(25)
#define BIT_SE_GENI_M_IRQ_EN_M_RX_FIFO_WATERMARK_EN  BIT(26)
#define BIT_SE_GENI_M_IRQ_EN_M_RX_FIFO_LAST_EN       BIT(27)
#define BIT_SE_GENI_M_IRQ_EN_M_TX_FIFO_RD_ERR_EN     BIT(28)
#define BIT_SE_GENI_M_IRQ_EN_M_TX_FIFO_WR_ERR_EN     BIT(29)
#define BIT_SE_GENI_M_IRQ_EN_M_TX_FIFO_WATERMARK_EN  BIT(30)
#define BIT_SE_GENI_M_IRQ_EN_M_SEC_IRQ_EN            BIT(31)

#define HWIO_SE_GENI_S_CMD0                 (HWIO_SE_GENI_BASE + 0x630)
#define BIT_SE_GENI_S_CMD0_S_OPCODE         GENBITS(31, 27)
#define SFT_SE_GENI_S_CMD0_S_OPCODE         27
#define BIT_SE_GENI_S_CMD0_S_PARAMS         GENBITS(26, 0)

// GENI_S_CMD_CTRL_REG
#define HWIO_SE_GENI_S_CMD_CTRL_REG (HWIO_SE_GENI_BASE + 0x634)
#define BIT_SE_GENI_S_DISABLE       BIT(0)
#define BIT_SE_GENI_S_CMD_ABORT     BIT(1)
#define BIT_SE_GENI_S_CMD_CANCEL    BIT(2)

#define HWIO_SE_GENI_S_IRQ_EN       (HWIO_SE_GENI_BASE + 0x644)
#define BIT_SE_GENI_S_IRQ_EN_S_CMD_DONE_EN          BIT(0)
#define BIT_SE_GENI_S_IRQ_EN_S_CMD_OVERRUN_EN       BIT(1)
#define BIT_SE_GENI_S_IRQ_EN_S_ILLEGAL_CMD_EN       BIT(2)
#define BIT_SE_GENI_S_IRQ_EN_S_CMD_FAILURE_EN       BIT(3)
#define BIT_SE_GENI_S_IRQ_EN_S_CMD_CANCEL_EN        BIT(4)
#define BIT_SE_GENI_S_IRQ_EN_S_CMD_ABORT_EN         BIT(5)
#define BIT_SE_GENI_S_IRQ_EN_S_GP_SYNC_IRQ_0_EN     BIT(8)
#define BIT_SE_GENI_S_IRQ_EN_S_GP_IRQ_0_EN          BIT(9)
#define BIT_SE_GENI_S_IRQ_EN_S_GP_IRQ_1_EN          BIT(10)
#define BIT_SE_GENI_S_IRQ_EN_S_GP_IRQ_2_EN          BIT(11)
#define BIT_SE_GENI_S_IRQ_EN_S_GP_IRQ_3_EN          BIT(12)
#define BIT_SE_GENI_S_IRQ_EN_S_GP_IRQ_4_EN          BIT(13)
#define BIT_SE_GENI_S_IRQ_EN_S_GP_IRQ_5_EN          BIT(14)
#define BIT_SE_GENI_S_IRQ_EN_S_IO_DATA_DEASSERT_EN  BIT(22)
#define BIT_SE_GENI_S_IRQ_EN_S_IO_DATA_ASSERT_EN    BIT(23)
#define BIT_SE_GENI_S_IRQ_EN_S_RX_FIFO_RD_ERR_EN    BIT(24)
#define BIT_SE_GENI_S_IRQ_EN_S_RX_FIFO_WR_ERR_EN    BIT(25)
#define BIT_SE_GENI_S_IRQ_EN_S_RX_FIFO_WATERMARK_EN BIT(26)
#define BIT_SE_GENI_S_IRQ_EN_S_RX_FIFO_LAST_EN      BIT(27)

// GENI_S_IRQ_CLEAR
#define HWIO_SE_GENI_S_IRQ_CLEAR               (HWIO_SE_GENI_BASE + 0x648)
#define BIT_SE_GENI_S_IRQ_CLEAR_CMD_DONE       BIT(0)
#define BIT_SE_GENI_S_IRQ_CLEAR_CMD_OVERRUN    BIT(1)
#define BIT_SE_GENI_S_IRQ_CLEAR_ILLEGAL_CMD    BIT(2)
#define BIT_SE_GENI_S_IRQ_CLEAR_CMD_FAILURE    BIT(3)
#define BIT_SE_GENI_S_IRQ_CLEAR_CMD_CANCEL     BIT(4)
#define BIT_SE_GENI_S_IRQ_CLEAR_CMD_ABORT      BIT(5)
#define BIT_SE_GENI_S_IRQ_CLEAR_GP_SYNC_IRQ_0  BIT(8)
#define BIT_SE_GENI_S_IRQ_CLEAR_GP_IRQ_0       BIT(9)
#define BIT_SE_GENI_S_IRQ_CLEAR_GP_IRQ_1       BIT(10)
#define BIT_SE_GENI_S_IRQ_CLEAR_GP_IRQ_2       BIT(11)
#define BIT_SE_GENI_S_IRQ_CLEAR_GP_IRQ_3       BIT(12)
#define BIT_SE_GENI_S_IRQ_CLEAR_GP_IRQ_4       BIT(13)
#define BIT_SE_GENI_S_IRQ_CLEAR_GP_IRQ_5       BIT(14)
#define BIT_SE_GENI_S_IRQ_CLEAR_IO_DATA_DEASSERT   BIT(22)
#define BIT_SE_GENI_S_IRQ_CLEAR_IO_DATA_ASSERT     BIT(23)
#define BIT_SE_GENI_S_IRQ_CLEAR_RX_FIFO_RD_ERR     BIT(24)
#define BIT_SE_GENI_S_IRQ_CLEAR_RX_FIFO_WR_ERR     BIT(25)
#define BIT_SE_GENI_S_IRQ_CLEAR_RX_FIFO_WATERMARK  BIT(26)
#define BIT_SE_GENI_S_IRQ_CLEAR_RX_FIFO_LAST       BIT(27)

// PACKING_CFG
#define HWIO_SE_GENI_TX_PACKING_CFG0   (HWIO_SE_GENI_BASE + 0x260)
#define HWIO_SE_GENI_TX_PACKING_CFG1   (HWIO_SE_GENI_BASE + 0x264)
#define HWIO_SE_GENI_RX_PACKING_CFG0   (HWIO_SE_GENI_BASE + 0x284)
#define HWIO_SE_GENI_RX_PACKING_CFG1   (HWIO_SE_GENI_BASE + 0x288)
#define HWIO_SE_GENI_BYTE_GRAN         (HWIO_SE_GENI_BASE + 0x254)

#define BIT_SE_GENI_RTX_PACKING_CFGn_VEC0_STOP       BIT(0)
#define BIT_SE_GENI_RTX_PACKING_CFGn_VEC0_LEN        BIT(1) | BIT(2) | BIT(3)
#define BIT_SE_GENI_RTX_PACKING_CFGn_VEC0_DIRECTION  BIT(4)
#define BIT_SE_GENI_RTX_PACKING_CFGn_VEC0_START_IDX  BIT(5) | BIT(6) | BIT(7) | BIT(8) | BIT(9)
#define BIT_SE_GENI_RTX_PACKING_CFGn_VEC1_STOP       BIT(10)
#define BIT_SE_GENI_RTX_PACKING_CFGn_VEC1_LEN        BIT(11) | BIT(12) | BIT(13)
#define BIT_SE_GENI_RTX_PACKING_CFGn_VEC1_DIRECTION  BIT(14)
#define BIT_SE_GENI_RTX_PACKING_CFGn_VEC1_START_IDX  BIT(15) | BIT(16) | BIT(17) | BIT(18) | BIT(19)
#define SFT_SE_GENI_RTX_PACKING_CFGn_VEC0_STOP       0
#define SFT_SE_GENI_RTX_PACKING_CFGn_VEC0_LEN        1
#define SFT_SE_GENI_RTX_PACKING_CFGn_VEC0_DIRECTION  4
#define SFT_SE_GENI_RTX_PACKING_CFGn_VEC0_START_IDX  5
#define SFT_SE_GENI_RTX_PACKING_CFGn_VEC1_STOP       10
#define SFT_SE_GENI_RTX_PACKING_CFGn_VEC1_LEN        11
#define SFT_SE_GENI_RTX_PACKING_CFGn_VEC1_DIRECTION  14
#define SFT_SE_GENI_RTX_PACKING_CFGn_VEC1_START_IDX  15

#define HWIO_SE_GENI_TX_FIFO0   (HWIO_SE_GENI_BASE + 0x700)
#define HWIO_SE_GENI_RX_FIFO0   (HWIO_SE_GENI_BASE + 0x780)

/* UART */
#define HWIO_SE_UART_LOOPBACK_CFG       (HWIO_SE_GENI_BASE + 0x22c)
#define HWIO_SE_UART_IO_MACRO_CTRL      (HWIO_SE_GENI_BASE + 0x240)
#define HWIO_SE_UART_TX_TRANS_CFG       (HWIO_SE_GENI_BASE + 0x25c)
#define HWIO_SE_UART_TX_WORD_LEN        (HWIO_SE_GENI_BASE + 0x268)
#define HWIO_SE_UART_TX_STOP_BIT_LEN    (HWIO_SE_GENI_BASE + 0x26c)
#define HWIO_SE_UART_TX_TRANS_LEN       (HWIO_SE_GENI_BASE + 0x270)
#define HWIO_SE_UART_RX_TRANS_CFG       (HWIO_SE_GENI_BASE + 0x280)
#define HWIO_SE_UART_RX_WORD_LEN        (HWIO_SE_GENI_BASE + 0x28c)
#define HWIO_SE_UART_RX_STALE_CNT       (HWIO_SE_GENI_BASE + 0x294)
#define HWIO_SE_UART_TX_PARITY_CFG      (HWIO_SE_GENI_BASE + 0x2a4)
#define HWIO_SE_UART_RX_PARITY_CFG      (HWIO_SE_GENI_BASE + 0x2a8)
#define HWIO_SE_UART_MANUAL_RFR         (HWIO_SE_GENI_BASE + 0x2ac)

/* uart se_m opcodes */
#define OPCODE_SE_M_UART_START_TX       0x1

/* uart se_s opcodes */
#define OPCODE_SE_S_SE_UART_START_RX    0x1
